booking/urls.py
from django.urls import path
from . import views

app_name = 'bookingpart'
urlpatterns = [
    path('bookings/', views.bookings, name='bookings'),
    path('bookings/create/', views.create, name='create'),
    path('bookings/<int:booking_id>/', views.details, name='details'),
    path('bookings/ack/', views.ack, name='ack'),
    path('bookings/ack/<int:booking_id>/', views.ackdetail, name='ack-detail')
]

login/urls.py
from django.urls import path
from . import views

app_name = 'loginpart'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/change/', views.change, name='change'),
]

booking/models.py
from django.db import models
from login import models as loginmodels


# Create your models here.
class Booking(models.Model):
    username = models.ForeignKey(loginmodels.User, on_delete=models.CASCADE)
    numboxes = models.IntegerField('Number of boxes', default=0)
    Daddress = models.CharField('Destination address', max_length=128, default=' ')
    Paddress = models.CharField('Pick up address', max_length=128, default=' ')
    shipdate = models.CharField('Shipment date', max_length=128, default=' ')
    messages = models.CharField('Messages to Shipper', max_length=128, default=' ')
    crttime = models.DateTimeField('Create time', auto_now_add=True)

    def __str__(self):
        return self.messages


class Ack(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    status = models.CharField('Status', max_length=64, default='To be approved')
    cost = models.CharField('Cost', max_length=64, default='35.00')
    pickuptime = models.CharField('Pick up time', max_length=64, default=' ')
    HBLnum = models.CharField('HBL number', max_length=128, default=' ')
    messagec = models.CharField('Messages to customer', max_length=128, default=' ')

    def __str__(self):
        return self.status

booking/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
import datetime
from . import models
from login import models as loginmodels


# Create your views here.
def bookings(request):
    if not request.session.get('is_login', None):
        # if the user is not log in
        return render(request, 'error.html', {"message": "Please login or register to access this resource"})
    # if the user logged in
    user_id = request.session.get('user_id', None)
    user = get_object_or_404(loginmodels.User, pk=user_id)
    try:
        results = user.booking_set.order_by('-crttime')  # results = all bookings of the current user
        return render(request, 'booking/bookings.html', {'results': results})
    except:
        return render(request, 'booking/bookings.html')


def create(request):
    if not request.session.get('is_login', None):
        # if the user is not log in
        return render(request, 'error.html', {"message": "Please login or register to access this resource"})
    listi = range(1, 11)  # i is used in #boxes
    listdate = []
    for i in range(5, 13):
        time = (datetime.datetime.now() + datetime.timedelta(days=i)).strftime('%Y-%m-%d, %A')
        listdate.append(time)
    if request.method == "POST":
        numboxes = request.POST.get('#boxes', None)
        Daddress = request.POST.get('daddress', None)
        Paddress = request.POST.get('paddress', None)
        shipdate = request.POST.get('shipdate', None)
        shiptime = request.POST.get('shiptime', None)
        messages = request.POST.get('messages', None)
        username = request.session.get('user_username', None)
        if not messages:
            messages = 'Null'
        user = get_object_or_404(loginmodels.User, username=username)
        new_booking = models.Booking()
        new_booking.username = user
        new_booking.numboxes = numboxes
        new_booking.Daddress = Daddress
        new_booking.Paddress = Paddress
        new_booking.shipdate = shipdate + ' ' + shiptime
        new_booking.messages = messages
        new_booking.save()
        new_ack = models.Ack()
        new_ack.booking = new_booking
        new_ack.cost = ('%.2f' % float(int(numboxes) * 35.00))
        new_ack.pickuptime = 'Null'
        new_ack.status = 'To be Approved'
        new_ack.HBLnum = 'Null'
        new_ack.messagec = 'Null'
        new_ack.save()
        return redirect('/bookings/')
    return render(request, 'booking/create.html', {'listdate': listdate, 'listi': listi})


def details(request, booking_id):
    if not request.session.get('is_login', None):
        # if the user is not log in
        return render(request, 'error.html', {"message": "Please login or register to access this resource"})
    # if the user logged in
    current_user = request.session.get('user_username', None)
    if current_user != 'susanto111':
        user = get_object_or_404(loginmodels.User, pk=request.session.get('user_id', None))
        try:
            results = user.booking_set.get(pk=booking_id)  # results = current booking
            acks = models.Ack.objects.get(booking=results)
            return render(request, 'booking/details.html', {
                'results': results,
                'acks': acks,
            })
        except:
            return render(request, 'error.html', {"message": "You have no access to this resource."})
    else:
        try:
            results = models.Booking.objects.get(pk=booking_id)
            acks = models.Ack.objects.get(booking=results)
            return render(request, 'booking/details.html', {
                'results': results,
                'acks': acks,
            })
        except:
            return render(request, 'error.html', {"message": "This resource does not exist"})


def ack(request):
    if not request.session.get('is_login', None):
        # if the user is not log in
        return render(request, 'error.html', {"message": "Please login or register to access this resource"})
    # if the user logged in
    current_user = request.session.get('user_username', None)
    if current_user != 'susanto111':
        # if the user is not susanto111
        return render(request, 'error.html', {"message": "You have no access to this resource"})
    # if the user is administrator
    allbookings = models.Booking.objects.order_by('-crttime')
    return render(request, 'booking/ack.html', {
        'allbookings': allbookings,
    })


def ackdetail(request, booking_id):
    if not request.session.get('is_login', None):
        # if the user is not log in
        return render(request, 'error.html', {"message": "Please login or register to access this resource"})
    current_user = request.session.get('user_username', None)
    if current_user != 'susanto111':
        # if the user is not susanto111
        return render(request, 'error.html', {"message": "You have no access to this resource"})
    thisbooking = models.Booking.objects.get(pk=booking_id)
    thisack = models.Ack.objects.get(booking=thisbooking)
    if request.method == "POST":
        status = request.POST.get('status', None)
        pickuptime = request.POST.get('pickup', None)
        HBLnum = request.POST.get('hbl', None)
        messagec = request.POST.get('messagec', None)
        if status != thisack.status or pickuptime != thisack.pickuptime or \
                HBLnum != thisack.HBLnum or messagec != thisack.messagec:
            thisack.status, thisack.pickuptime = status, pickuptime
            thisack.HBLnum, thisack.messagec = HBLnum, messagec
            thisack.save()
            booking_user = thisbooking.username  # booking_user is the user of this booking
            email = booking_user.email
            send_email(status, pickuptime, HBLnum, messagec, email)
        return redirect('/bookings/ack/')
    return render(request, 'booking/ackdetail.html', {
        'booking_id': booking_id,
        'thisack': thisack,
        'thisbooking': thisbooking,
    })


def send_email(status, pickuptime, HBLnum, messagec, email):
    from django.core.mail import EmailMultiAlternatives
    subject, from_email = 'Ack Updated - from Shipping Site', 'forshippingsite@sina.com'
    text_content = 'Dear Customer,' \
                   'The shipper just updated the Ack of your booking.' \
                   'Please login and check it via home - bookings - view details..'
    html_content = '<p>Dear Customer, </p>' \
                   '<p>The shipper just updated the Ack of your booking. The new Ack is listed below: </p> ' \
                   '<p> <strong>Status:</strong> {}</p>'\
                   '<p> <strong>Pick up date and time: </strong> {} </p>' \
                   '<p> <strong>HBL number: </strong> {} </p>' \
                   '<p> <strong>Messages to customer: </strong> {} </p>' \
                   '<p> For more details,please login and checkout.</p>'.format(status, pickuptime, HBLnum, messagec)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

booking/templates/booking/ack.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Ack - Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
         <div style="margin-top: 75px;">
             <h2>Booking List</h2>
             <em>All bookings are listed below, you can see details via "Details" </em><hr>
         </div>
             {% if allbookings %}
                 <table class="table table-striped" style="width: 100%">
                 <thead>
                 <tr>
                     <th>ID</th>
                     <th>Create time</th>
                     <th>Username</th>
                     <th>Operations</th>
                     <th>Status</th>
                 </tr>
                 </thead>
                 <tbody>
                 {% for booking in allbookings %}
                     <tr>
                     <td>{{ booking.id }}</td>
                     <td>{{ booking.crttime }}</td>
                     <td>{{ booking.username}}</td>
                     <td><a href={% url 'bookingpart:details' booking.id %}>Details</a>
                         /<a href={% url 'bookingpart:ack-detail' booking.id %}>Ack</a></td>
                     <td>{{ booking.ack_set.get}} </td>
                     </tr>
                 {% endfor %}
                 </tbody>
                 </table>
             {% else %}
                 <p><em>You have no bookings currently</em></p>
             {% endif %}
    {% if status %}
        <p>hello</p>
    {% endif %}

    </div>  <!--end of container-->

{% endblock %}

booking/templates/booking/ackdetail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Create or Edit Ack - Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
      <div style="margin-top: 75px;" name="title">
          <h2>Edit</h2>
          <em>Edit an ack for current booking, you can also send an email to customer via this page</em><hr>
      </div> <!--end of title-->
      <div name="edit ack" style="width: 500px">
          <form class="form-horizontal" action="{% url 'bookingpart:ack-detail' booking_id %}" method="POST" role="form">
              {% csrf_token %}
            <p>
              <label for="id_status">Status</label><br/>
              <select class="form-control" id="id_status" name="status" >
                  <option>To be Approved</option>
                  <option>Request Accepted</option>
                  <option>Ready for Pick up</option>
                  <option>Scheduled</option>
                  <option>To be Shipped</option>
                  <option>Shipped</option>
                  <option>Arrived at Destination</option>
                  <option>Delivered</option>
                  <option>Delivery Delayed</option>
              </select>
              <span class="help-block">Current status: {{ thisack.status }}</span>
              <label for="id_pickup">Pick up date and time</label><br />
              {% if thisack.pickuptime == 'Null' %}
                  <input class="form-control" maxlength="64" type="text" id="id_pickup" value="{{ thisbooking.shipdate }}" name="pickup"  required />
              {% else %}
                  <input class="form-control" maxlength="64" type="text" id="id_pickup" value="{{ thisack.pickuptime }}" name="pickup"  required />
              {% endif %}
              <label for="id_hbl">HBL number</label><br />
              <input class="form-control" maxlength="128" type="text" id="id_hbl" value="{{ thisack.HBLnum }}" name="hbl" required />
              <label for="id_messagec">Message to Customer</label><br />
              <textarea class="form-control" rows="4" id="id_messagec" name="messagec" >{{ thisack.messagec }}</textarea>
            </p>
              <input class="btn btn-primary" type="submit" value="Submit">
              <a href="/bookings/ack/" class="btn btn-default" role="button">Cancel</a>
          </form>
      </div>  <!--end of edit ack-->

      <div></div>


    </div> <!--end of container-->
{% endblock %}

booking/templates/booking/bookings.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Bookings - Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
      <div style="margin-top: 75px;">
          <h2>Booking List</h2>
          <em>All your bookings are listed below, you can check existing bookings or create a new one</em><hr>
          <p><a href="create/" class="btn btn-primary btn-sm" role="button">Create New</a></p>
      </div>
          {% if results %}
              <table class="table table-striped" style="width: 100%">
              <thead>
                <tr>
                  <th>Create time</th>
                  <th>#Boxes</th>
                  <th>Details</th>
                </tr>
              </thead>
              <tbody>
              {% for booking in results %}
                  <tr>
                  <td>{{ booking.crttime }}</td>
                      <td>{{ booking.numboxes }}</td>
                      <td><a href={% url 'bookingpart:details' booking.id %}>View Details</a></td>
                  </tr>
              {% endfor %}
              </tbody>
              </table>
          {% else %}
              <p><em>You have no bookings currently, click <a href="create/">here</a> to create one right now.</em></p>
          {% endif %}
    </div>
{% endblock %}

booking/templates/booking/create.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Create - Shipping Site</title>
{% endblock %}

{% block content %}

    <div class="container">
         <div style="margin-top: 75px; width: 450px">
             <h2>Create a booking</h2>
             <em>Create your bookings here</em><hr>
             <form class="form-horizontal" action="/bookings/create/" method="POST" role="form">
                 {% csrf_token %}
                 <label for="id_#boxes">#Boxes</label><br />
                 <select class="form-control" id="id_#boxes" name="#boxes">
                     {% for i in listi %}
                         <option>{{ i }}</option>
                     {% endfor %}
                 </select>
                 <p>
                    <label for="id_daddress">Destination Address</label><br />
                    <input class="form-control" maxlength="64" type="text" id="id_daddress" name="daddress" required />
                 </p>
                 <p>
                    <label for="id_paddress">Pick Up Address</label><br />
                    <input class="form-control" maxlength="64" type="text" id="id_paddress" name="paddress" required />
                 </p>
                 <p>
                 <label for="id_shipdate">Preferred Shipment Date</label><br />
                 <select class="form-control" id="id_shipdate" name="shipdate">
                     {% for date in listdate %}
                         <option>{{date}}</option>
                     {% endfor %}
                 </select>
                 </p>
                 <p>
                 <label for="id_shipdate">Preferred Shipment Time</label><br />
                 <select class="form-control" id="id_shiptime" name="shiptime">
                     <option>10:00 - 12:00</option>
                     <option>14:00 - 16:00</option>
                     <option>16:00 - 18:00</option>
                 </select>
                 </p>
                 <p>
                    <label for="id_messages">Messages</label><br />
                    <textarea class="form-control" rows="4" id="id_messages" name="messages"></textarea>
                 </p>
                 <input class="btn btn-default" type="submit" value="Create">
                 <a href="/bookings/" class="btn btn-default" role="button">Cancel</a>
             </form>
         </div>
    </div>

{% endblock %}

booking/templates/booking/details.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Details - Shipping Site</title>
{% endblock %}

{% block content %}

    <div class="container">
         <div style="margin-top: 75px; width: 470px">
             <h2>Details</h2>
             <em>Booking id: No.{{ results.id }}</em><hr>
             <div style="float:left; width:200px" name="left">
                 <p class="text-right"><strong>Number of Boxes:</strong></p>
                 <p class="text-right"><strong>Destination Address:</strong></p>
                 <p class="text-right"><strong>Pick Up Address:</strong></p>
                 <p class="text-right"><strong>Possible Shipment date:</strong></p>
                 <p class="text-right"><strong>Messages to Shipper:</strong></p>
                 <br />
                 <p class="text-right"><strong>Status:</strong></p>
                 <p class="text-right"><strong>Pick up date and time: </strong></p>
                 <p class="text-right"><strong>Price:</strong></p>
                 <p class="text-right"><strong>HBL Number:</strong></p>
                 <p class="text-right"><strong>Messages to Customer:</strong></p>
             </div>
             <div style="width:240px; float:right" name="right">
                 <p>{{ results.numboxes }}</p>
                 <p>{{ results.Daddress }}</p>
                 <p>{{ results.Paddress }}</p>
                 <p>{{ results.shipdate }}</p>
                 <p>{{ results.messages }}</p>
                 <br />
                 {% if acks %}
                     <p> {{ acks.status }}</p>
                     <p> {{ acks.pickuptime }}</p>
                     <p> AUD {{ acks.cost }}</p>
                     <p> {{ acks.HBLnum }}</p>
                     <p> {{ acks.messagec }}</p>
                 {% else %}
                     <p> To be created </p>
                     <p> To be created </p>
                     <p> AUD {{ acks.cost }}</p>
                     <p> To be created </p>
                     <p> To be created </p>
                 {% endif %}
                 <br/>
                 <p class="text-right"><a href="{% url 'bookingpart:bookings' %}">Back</a></p>
             </div>
         </div>
    </div> <!--end of container-->
{% endblock %}