login/urls.py
from django.urls import path
from . import views

app_name = 'loginpart'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/change/', views.change, name='change'),
]

login/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    # username should be unique, so we can figure out different users
    username = models.CharField(max_length=32, unique=True)  # 5-32
    name = models.CharField(max_length=64)
    homeAddress = models.CharField(max_length=128)
    password = models.CharField(max_length=256)  # 5-32, max_length=256 was assigned for safety
    phoneNo = models.CharField(max_length=16)
    email = models.EmailField(max_length=64)

    def __str__(self):
        return self.username

login/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="username", max_length=128)
    password = forms.CharField(label="password", max_length=256, widget=forms.PasswordInput)

login/views.py
import re
from . import models
from django.shortcuts import render, redirect, get_object_or_404


# Create your views here.
def index(request):
    return render(request, 'login/index.html')


def login(request):
    if request.session.get('is_login', None):
        # repeat login is not allowed, so if the user has logged in, report error.
        return render(request, 'error.html', {
            "message": "You've already logged in, repeat login is not allowed."})
    if request.method == "POST":
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        remember = request.POST.get('remember', None)
        # This None means that if we cannot find this keyword, return None.
        if remember:
            request.session.set_expiry(60*60*24*3)  # cookie will be remembered for 3 days
        if username and password:
            umatch = username.strip()  # remove space in username
            pmatch = password.strip()
            message = "Invalid input."
            if umatch and pmatch:  # if username and password are legal
                try:
                    user = models.User.objects.get(username=username)
                    if user.password == password:
                        request.session['is_login'] = True
                        request.session['user_id'] = user.id
                        request.session['user_username'] = user.username
                        return redirect('/index/')
                    else:
                        message = "Wrong password, please try again."
                except:
                    message = "Username does not exist, please register."
            return render(request, 'login/login.html', {"message": message})
    return render(request, 'login/login.html')


def register(request):
    if request.session.get('is_login', None):
        # status login is not allowed
        return render(request, 'error.html', {"message": "You've already logged in."})
    if request.method == "POST":
        username = request.POST.get('username', None)
        name = request.POST.get('name', None)
        address = request.POST.get('address', None)
        phone = request.POST.get('phone', None)
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)
        password2 = request.POST.get('password2', None)
        if password != password2:
            message = "Passwords are different, please input again."
            return render(request, 'login/register.html', {'message': message})
        umatch = re.match(r'^[\d\w_]{5,32}$', username)  # the length of username should be 5~32
        pmatch = re.match(r'^[*?_\w\d]{6,32}$', password)  # the length of password should be 6~32
        if umatch and pmatch:  # if username, password and phone are valid
            same_username = models.User.objects.filter(username=username)
            same_email = models.User.objects.filter(email=email)
            if same_username:
                # same username is not allowed
                message = "Username already exists, please login or create a new one"
                return render(request, 'login/register.html', {'message': message})
            if same_email:
                # same email is not allowed
                message = "Email address already exists, please login or use a new one"
                return render(request, 'login/register.html', {'message': message})
            # if username, password, and email address are fine, then:
            new_user = models.User()  # get a new User instance
            new_user.username = username
            new_user.name = name
            new_user.homeAddress = address
            new_user.phoneNo = phone
            new_user.email = email
            new_user.password = password
            new_user.save()  # save the info of new users
            send_email(username, password, email)
            return redirect('/login/')
        else:   # if username or password is invalid
            message = ""
            if not umatch:
                message = "Invalid username, can only contain A-Z, a-z, 0-9, the length should be 5~32. "
            if not pmatch:
                message = message + \
                          "Invalid password, can only contain A-Z, a-z, 0-9 and * _ ?, the length should be 6~32"
            return render(request, 'login/register.html', {'message': message})
    return render(request, 'login/register.html')


def logout(request):
    if request.session.get('is_login', None):
        request.session.flush()
    return redirect("/index/")


def profile(request):
    user = get_object_or_404(models.User, pk=request.session.get('user_id', None))
    if request.method == "POST":
        name = request.POST.get('name', None)
        address = request.POST.get('address', None)
        phone = request.POST.get('phone', None)
        email = request.POST.get('email', None)
        same_email = models.User.objects.filter(email=email)
        if same_email:
            # same email is not allowed
            message = "Email address already exists, please use another one"
            return render(request, 'login/profile.html', {'message': message})
        new_user = models.User.objects.get(pk=request.session.get('user_id', None))
        new_user.name = name
        new_user.homeAddress = address
        new_user.phoneNo = phone
        new_user.email = email
        new_user.save()  # save the info of current user
        return redirect('/index/')
    return render(request, 'login/profile.html', {'user': user})


def change(request):
    if request.method == "POST":
        prepassword = request.POST.get('prepassword', None)
        newpassword = request.POST.get('newpassword', None)
        password2 = request.POST.get('password2', None)
        user = get_object_or_404(models.User, pk=request.session.get('user_id', None))
        if newpassword != password2:
            message = "Passwords are different, please input again."
            return render(request, 'login/change.html', {'message': message})
        if prepassword != user.password:
            message = "Previous password is wrong, please try again."
            return render(request, 'login/change.html', {'message': message})
        newmatch = re.match(r'^[*?_\w\d]{6,32}$', newpassword)  # the length of password should be 6~32
        if newmatch:
            new_user = models.User.objects.get(pk=request.session.get('user_id', None))
            new_user.password = newpassword
            new_user.save()
            request.session.flush()
            return redirect('/index/')
        else:
            message = "Invalid password, can only contain A-Z, a-z, 0-9 and * _ ?, the length should be 6~32"
            return render(request, 'login/change.html', {'message': message})
    return render(request, 'login/change.html')


def send_email(username, password, email):
    from django.core.mail import EmailMultiAlternatives
    subject, from_email = 'Register successfully - from Shipping Site', 'forshippingsite@sina.com'
    text_content = 'You have created an account successfully! Please remember your username and password.'
    html_content = '<p>Dear Customer: </p>' \
                   '<p>&emsp;&emsp;You have created an account successfully!</p>' \
                   '<p>&emsp;&emsp;Please remember your username and password listed below:' \
                   '<p> <strong>&emsp;&emsp;Username: </strong> {} </p>'\
                   '<p> <strong>&emsp;&emsp;Password: </strong> {} </p>'.format(username, password)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

login/templates/login/change.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Change Password - Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
      <div  style="float: left; margin-top: 75px; width: 650px" >
          <h2>Account Management</h2>
          <em>You can edit your personal profile or change your password on this page.</em><hr>
          <div style="float: left; width: 200px" name="tablist">
              <ul class="nav nav-pills nav-stacked" role="tablist" style="margin-top: 20px">
                  <li><a href="{% url 'loginpart:profile' %}">Profile</a></li>
                  <li class="active"><a href="{% url 'loginpart:change' %}">Change Password</a></li>
              </ul>
          </div>  <!--end of tablist-->
          <div style="float: right; width: 400px">
              <form class="form-horizontal" action="{% url 'loginpart:change' %}" method="POST" role="form">
                  {% if message %}
                      <div style = "font-size: small;" class="alert alert-warning">{{ message }}</div>
                  {% endif %}
                  {% csrf_token %}
                  <label for="id_prepassword">Previous Password</label><br />
                  <input class="form-control" minlength="6" maxlength="32" type="password" id="id_prepassword" name="prepassword" required />

                  <label for="id_newpassword">New Password</label><br />
                  <input class="form-control" minlength="6" maxlength="32" type="password" id="id_prepassword" name="newpassword" autofocus required />

                  <label for="id_password2">Confirm Your Password</label><br />
                  <input class="form-control" minlength="6" maxlength="32" type="password" id="id_password2" name="password2" required />

                  <br/><br/>
                  <input class="btn btn-primary" type="submit" value="Submit">&ensp;
                  <a href="{% url 'loginpart:index' %}" class="btn btn-default" role="button">Cancel</a>
              </form>
          </div>
      </div>
    </div>  <!--end of container-->
{% endblock %}

login/templates/login/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
          <img src="{% static "images/banner3.svg" %}" class="img-responsive" width="100%">
          <h1>Susanto's Shipping Site</h1>
          <p>Customers can making a booking or see their ACK status after register or login</p>
          <p>Waiting for more information</p>
          <p>...</p>

          {% if message %}
              <p><em>{{ message }}</em></p>
          {% else %}
              <p><a class="btn btn-lg btn-primary" href="/login/" role="button">For more information, please register or login &raquo;</a></p>
          {% endif %}
      </div>

      <div class="container">
          <div style="float: left; width: 25%" >
              <h2>Our Shop</h2>
              <li>Melbourne, VIC, 3000</li>
              <li>Carlton, VIC, 3053</li>
              <li>Yarra, comming soon...</li>
          </div>
          <div style="float: left; width: 25%" >
              <h2>Sending</h2>
              <li>Booking now!</li>
          </div>
          <div style="float: left; width: 25%" >
              <h2>Receiving</h2>
              <li>We can pick boxes up at your door!</li>
              <li>Just to make this page longer</li>

          </div>
          <div style="float: left; width: 25%" >
              <h2>Insurance</h2>
              <li>About boxes' insurance</li>
              <li>Making this page longer</li>
              <li>...</li>
              <li>...</li>
              <li>...</li>
              <li>...</li>
              <h2>Welcome Back!</h2>
          </div>
       </div>
    </div> <!-- /container -->
{% endblock %}

login/templates/login/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Login - Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
      <div  style="float: left; margin-top: 75px; width: 400px" >
        <h2>Log in</h2>
        <em>Use a valid account to log in.</em><hr>
        <form class="form-horizontal" action="/login/" method="POST" role="form">
            {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            {% csrf_token %}
            <p>
                <label for="id_username">Username</label><br />
                <input class="form-control" minlength="5" maxlength="64" type="text" id="id_username" name="username" placeholder="Username" autofocus required />
            </p>
            <p>
                <label for="id_password">Password</label><br />
                <input class="form-control" minlength="6" maxlength="32" type="password" id="id_password" name="password" placeholder="Password" required />
            </p>
            <input type="checkbox" id="id_remember" name="remember">
            <span>Remember me?</span><br/><br/>
            <input class="btn btn-primary" type="submit" value="Login">
            <a href="/index/" class="btn btn-default" role="button">Cancel</a>

        </form>
        <br/><br/>
        <p>Still not a member?<br/><a href="/register/">Click here to create a new account!</a></p>
      </div>
    </div> <!--end of container-->
{% endblock %}

login/templates/login/profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Edit Profile - Shipping Site</title>
{% endblock %}

{% block content %}
    <div class="container">
      <div  style="float: left; margin-top: 75px; width: 650px" >
          <h2>Account Management</h2>
          <em>You can edit your personal profile or change your password on this page.</em><hr>
          <div style="float: left; width: 200px" name="tablist">
              <ul class="nav nav-pills nav-stacked" role="tablist" style="margin-top: 20px">
                  <li class="active"><a href="{% url 'loginpart:profile' %}">Profile</a></li>
                  <li><a href="{% url 'loginpart:change' %}">Change Password</a></li>
              </ul>
          </div>  <!--end of tablist-->
          <div style="float: right; width: 400px">
              <form class="form-horizontal" action="{% url 'loginpart:profile' %}" method="POST" role="form">
                  {% if message %}
                      <div style = "font-size: small;" class="alert alert-warning">{{ message }}</div>
                  {% endif %}
                  {% csrf_token %}
                  <label for="id_username">Username</label><br/>
                  <input class="form-control" id="id_username" type="text" placeholder="{{ user.username }}" disabled>

                  <label for="id_name">Name</label><br />
                  <input class="form-control" maxlength="64" type="text" id="id_name" name="name" value="{{ user.name }}" required/>

                  <label for="id_address">Home Address</label><br />
                  <input class="form-control" maxlength="128" type="text" id="id_address" name="address" value="{{ user.homeAddress }}" required />

                  <label for="id_phone">Phone Number</label><br />
                  <input class="form-control" minlength="9" maxlength="16" type="text" id="id_phone" name="phone"
                         onkeyup="value=value.replace(/[^\d+]/g,'')"  value="{{ user.phoneNo }}" required />

                  <label for="id_email">Email Address</label><br />
                  <input class="form-control" maxlength="64" type="email" id="id_email" name="email" value="{{ user.email }}" required />

                  <br/><br/>
                  <input class="btn btn-primary" type="submit" value="Submit">&nbsp;
                  <a href="{% url 'loginpart:index' %}" class="btn btn-default" role="button">Cancel</a>
              </form>
          </div>
      </div>
    </div>  <!--end of container-->
{% endblock %}

login/templates/login/register.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>Register - Shipping Site</title>
{% endblock %}

{% block content %}
  <div class="container">
    <div  style="float: left; margin-top: 75px; width: 400px" >
        <h2>Register</h2>
        <em>Create a new account.</em><hr>
        <form class="form-horizontal" action="/register/" method="POST" role="form">
            {% if message %}
                <div style = "font-size: small;" class="alert alert-warning">{{ message }}</div>
            {% endif %}
            {% csrf_token %}
            <p>
                <label for="id_username">Username</label><br />
                <input class="form-control" minlength="5" maxlength="64" type="text" id="id_username" name="username" autofocus required />
            </p>
            <p>
                <label for="id_name">Name</label><br />
                <input class="form-control" maxlength="64" type="text" id="id_name" name="name" required />
            </p>
            <p>
                <label for="id_address">Home Address</label><br />
                <input class="form-control" maxlength="128" type="text" id="id_address" name="address" required />
            </p>
            <p>
                <label for="id_phone">Phone Number</label><br />
                <input class="form-control" minlength="9" maxlength="16" type="text" id="id_phone" name="phone" onkeyup="value=value.replace(/[^\d+]/g,'')" required />
            </p>
            <p>
                <label for="id_email">Email Address</label><br />
                <input class="form-control" maxlength="64" type="email" id="id_email" name="email" required />
            </p>
            <p>
                <label for="id_password">Password</label><br />
                <input class="form-control" minlength="6" maxlength="32" type="password" id="id_password" name="password" autofocus required />
            </p>
             <p>
                <label for="id_password2">Confirm Your Password</label><br />
                <input class="form-control" minlength="6" maxlength="32" type="password" id="id_password2" name="password2" required />
            </p>
            <br/><br/>
            <input class="btn btn-primary" type="submit" value="Submit">
            <a href="/index/" class="btn btn-default" role="button">Cancel</a>
        </form>
    </div>
  </div>
{% endblock %}